/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.userInterface;

/**
 *
 * @author pedro
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxUCsRegistadas = new javax.swing.JCheckBox();
        jCheckBoxUsersRegistered = new javax.swing.JCheckBox();
        jCheckBoxTurnosRegistados = new javax.swing.JCheckBox();
        jCheckBoxLoginsActive = new javax.swing.JCheckBox();
        jCheckBoxShiftsAssigned = new javax.swing.JCheckBox();
        jButtonImportUCs = new javax.swing.JButton();
        jButtonImportUsers = new javax.swing.JButton();
        jButtonImportShifts = new javax.swing.JButton();
        jButtonActivateLogins = new javax.swing.JButton();
        jButtonActivateShifts = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonAddShift = new javax.swing.JButton();
        jButtonRemoveShift = new javax.swing.JButton();
        jButtonConsultUC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBoxUCsRegistadas.setText("UCs registadas");

        jCheckBoxUsersRegistered.setText("Utilizadores registados");

        jCheckBoxTurnosRegistados.setText("Turnos registados");

        jCheckBoxLoginsActive.setText("Logins ativos");

        jCheckBoxShiftsAssigned.setText("Turnos atribuidos");

        jButtonImportUCs.setText("Importar UCs");
        jButtonImportUCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportUCsActionPerformed(evt);
            }
        });

        jButtonImportUsers.setText("Importar Utilizadores");
        jButtonImportUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportUsersActionPerformed(evt);
            }
        });

        jButtonImportShifts.setText("Importar turnos");
        jButtonImportShifts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportShiftsActionPerformed(evt);
            }
        });

        jButtonActivateLogins.setText("Ativar Logins");
        jButtonActivateLogins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivateLoginsActionPerformed(evt);
            }
        });

        jButtonActivateShifts.setText("Atribuir turnos");
        jButtonActivateShifts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivateShiftsActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonAddShift.setText("Adicionar Turno");
        jButtonAddShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddShiftActionPerformed(evt);
            }
        });

        jButtonRemoveShift.setText("Remover Turno");
        jButtonRemoveShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveShiftActionPerformed(evt);
            }
        });

        jButtonConsultUC.setText("Consultar UCs");
        jButtonConsultUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultUCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonImportShifts)
                    .addComponent(jButtonImportUsers)
                    .addComponent(jButtonImportUCs)
                    .addComponent(jButtonActivateLogins)
                    .addComponent(jButtonActivateShifts))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxLoginsActive)
                    .addComponent(jCheckBoxShiftsAssigned)
                    .addComponent(jCheckBoxUsersRegistered)
                    .addComponent(jCheckBoxUCsRegistadas)
                    .addComponent(jCheckBoxTurnosRegistados))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddShift)
                    .addComponent(jButtonRemoveShift)
                    .addComponent(jButtonConsultUC))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonImportUCs)
                            .addComponent(jCheckBoxUCsRegistadas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonImportUsers)
                            .addComponent(jCheckBoxUsersRegistered))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonImportShifts)
                            .addComponent(jCheckBoxTurnosRegistados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonActivateLogins)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBoxLoginsActive)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonActivateShifts)
                            .addComponent(jCheckBoxShiftsAssigned)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAddShift)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRemoveShift)
                                .addGap(71, 71, 71)
                                .addComponent(jButtonConsultUC))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddShiftActionPerformed

    private void jButtonImportUCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportUCsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImportUCsActionPerformed

    private void jButtonImportUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImportUsersActionPerformed

    private void jButtonImportShiftsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportShiftsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImportShiftsActionPerformed

    private void jButtonActivateLoginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActivateLoginsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActivateLoginsActionPerformed

    private void jButtonActivateShiftsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActivateShiftsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActivateShiftsActionPerformed

    private void jButtonRemoveShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveShiftActionPerformed

    private void jButtonConsultUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultUCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActivateLogins;
    private javax.swing.JButton jButtonActivateShifts;
    private javax.swing.JButton jButtonAddShift;
    private javax.swing.JButton jButtonConsultUC;
    private javax.swing.JButton jButtonImportShifts;
    private javax.swing.JButton jButtonImportUCs;
    private javax.swing.JButton jButtonImportUsers;
    private javax.swing.JButton jButtonRemoveShift;
    private javax.swing.JCheckBox jCheckBoxLoginsActive;
    private javax.swing.JCheckBox jCheckBoxShiftsAssigned;
    private javax.swing.JCheckBox jCheckBoxTurnosRegistados;
    private javax.swing.JCheckBox jCheckBoxUCsRegistadas;
    private javax.swing.JCheckBox jCheckBoxUsersRegistered;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
