/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.userInterface;

import main.sgt.SGT;
import main.sgt.exceptions.BadlyFormatedFileException;

import javax.swing.*;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author pedro
 */
@SuppressWarnings({"FieldCanBeLocal", "unused", "Convert2Lambda", "Anonymous2MethodRef", "TryWithIdenticalCatches"})
public class JAdmin extends javax.swing.JFrame implements Observer {

    private SGT sgt;
    private JButton[] buttons = new JButton[5];
    private JCheckBox[] checkBoxes = new JCheckBox[5];
    private final JFileChooser fc = new JFileChooser();

    /**
     * Creates new form Admin
     * @param sgt Business logic instance
     */
    JAdmin(SGT sgt) {
        this.sgt = sgt;
        initComponents();
        this.sgt.addObserver(this);
        initLists();
        initCheckBoxes();
        //for(int i=0;i<5;i++) this.checkBoxes[i].setEnabled(false);
    }

    private void initLists() {
        this.buttons[0] = this.jButtonImportUCs;
        this.buttons[1] = this.jButtonImportUtilizadores;
        this.buttons[2] = this.jButtonImportTurnos;
        this.buttons[3] = this.jButtonActivateLogins;
        this.buttons[4] = this.jButtonAssignShifts;
        this.checkBoxes[0] = this.jCheckBoxUCsRegistadas;
        this.checkBoxes[1] = this.jCheckBoxUsersRegistered;
        this.checkBoxes[2] = this.jCheckBoxTurnosRegistados;
        this.checkBoxes[3] = this.jCheckBoxLoginsActive;
        this.checkBoxes[4] = this.jCheckBoxShiftsAssigned;
        for(int i=0;i<5;i++){
            for (MouseListener aMl : this.checkBoxes[i].getListeners(MouseListener.class))
                this.checkBoxes[i].removeMouseListener(aMl);
            InputMap im = this.checkBoxes[i].getInputMap();
            im.put(KeyStroke.getKeyStroke("SPACE"), "none");
            im.put(KeyStroke.getKeyStroke("released SPACE"), "none");
        }
    }

    private void initCheckBoxes() {
        int state;
        if(this.sgt.isTurnosAtribuidos()){
            state = 5;
        }else if(this.sgt.isLoginsAtivos()){
            state = 4;
        }else if(this.sgt.isTurnosRegistados()){
            state = 3;
        }else if(this.sgt.isUsersRegistados()){
            state = 2;
        }else if(this.sgt.isUcsRegistadas()){
            state = 1;
        }else {
            state = 0;
        }
        for(int i=0;i<state;i++){
            this.checkBoxes[i].setSelected(true);
        }
    }

    private void disableFrom(int index){
        while (index<5) {
            this.buttons[index].setEnabled(false);
            this.checkBoxes[index++].setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxUCsRegistadas = new javax.swing.JCheckBox();
        jCheckBoxUsersRegistered = new javax.swing.JCheckBox();
        jCheckBoxTurnosRegistados = new javax.swing.JCheckBox();
        jCheckBoxLoginsActive = new javax.swing.JCheckBox();
        jCheckBoxShiftsAssigned = new javax.swing.JCheckBox();
        jButtonImportUCs = new javax.swing.JButton();
        jButtonImportUtilizadores = new javax.swing.JButton();
        jButtonImportTurnos = new javax.swing.JButton();
        jButtonActivateLogins = new javax.swing.JButton();
        jButtonAssignShifts = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonAddShift = new javax.swing.JButton();
        jButtonRemoveShift = new javax.swing.JButton();
        jButtonConsultUC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBoxUCsRegistadas.setText("UCs registadas");

        jCheckBoxUsersRegistered.setText("Utilizadores registados");

        jCheckBoxTurnosRegistados.setText("Turnos registados");

        jCheckBoxLoginsActive.setText("Logins ativos");

        jCheckBoxShiftsAssigned.setText("Turnos atribuidos");

        jButtonImportUCs.setText("Importar UCs");
        jButtonImportUCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportUCsActionPerformed(evt);
            }
        });

        jButtonImportUtilizadores.setText("Importar Utilizadores");
        jButtonImportUtilizadores.setEnabled(this.sgt.isUcsRegistadas());
        jButtonImportUtilizadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportUtilizadoresActionPerformed(evt);
            }
        });

        jButtonImportTurnos.setText("Importar turnos");
        jButtonImportTurnos.setEnabled(this.sgt.isUsersRegistados());
        jButtonImportTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportTurnosActionPerformed(evt);
            }
        });

        jButtonActivateLogins.setText("Ativar Logins");
        jButtonActivateLogins.setEnabled(this.sgt.isTurnosRegistados());
        jButtonActivateLogins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivateLoginsActionPerformed(evt);
            }
        });

        jButtonAssignShifts.setText("Atribuir turnos");
        jButtonAssignShifts.setEnabled(this.sgt.isLoginsAtivos());
        jButtonAssignShifts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignShiftsActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonAddShift.setText("Adicionar Turno");
        jButtonAddShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddShiftActionPerformed(evt);
            }
        });

        jButtonRemoveShift.setText("Remover Turno");
        jButtonRemoveShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveShiftActionPerformed(evt);
            }
        });

        jButtonConsultUC.setText("Consultar UCs");
        jButtonConsultUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultUCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonImportTurnos)
                    .addComponent(jButtonImportUtilizadores)
                    .addComponent(jButtonImportUCs)
                    .addComponent(jButtonActivateLogins)
                    .addComponent(jButtonAssignShifts))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxLoginsActive)
                    .addComponent(jCheckBoxShiftsAssigned)
                    .addComponent(jCheckBoxUsersRegistered)
                    .addComponent(jCheckBoxUCsRegistadas)
                    .addComponent(jCheckBoxTurnosRegistados))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddShift)
                    .addComponent(jButtonRemoveShift)
                    .addComponent(jButtonConsultUC))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonImportUCs)
                            .addComponent(jCheckBoxUCsRegistadas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonImportUtilizadores)
                            .addComponent(jCheckBoxUsersRegistered))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonImportTurnos)
                            .addComponent(jCheckBoxTurnosRegistados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonActivateLogins)
                            .addComponent(jCheckBoxLoginsActive))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAssignShifts)
                            .addComponent(jCheckBoxShiftsAssigned)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAddShift)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRemoveShift)
                                .addGap(71, 71, 71)
                                .addComponent(jButtonConsultUC))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddShiftActionPerformed

    private void jButtonImportUCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportUCsActionPerformed
        int returnVal = fc.showOpenDialog(this);
        if(returnVal==JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            try {
                this.sgt.importUCs(file.getAbsolutePath());
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (BadlyFormatedFileException e) {
                JOptionPane.showMessageDialog(this,"Badly formated file","Bad file",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonImportUCsActionPerformed

    private void jButtonImportUtilizadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportUtilizadoresActionPerformed
        int returnVal = fc.showOpenDialog(this);
        if(returnVal==JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            try {
                this.sgt.importUtilizadores(file.getAbsolutePath());
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (BadlyFormatedFileException e) {
                JOptionPane.showMessageDialog(this,"Badly formated file","Bad file",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonImportUtilizadoresActionPerformed

    private void jButtonImportTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportTurnosActionPerformed
        int returnVal = fc.showOpenDialog(this);
        if(returnVal==JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            try {
                this.sgt.importTurnos(file.getAbsolutePath());
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (BadlyFormatedFileException e) {
                JOptionPane.showMessageDialog(this,"Badly formated file","Bad file",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonImportTurnosActionPerformed

    private void jButtonActivateLoginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActivateLoginsActionPerformed
        this.sgt.activateLogins();
    }//GEN-LAST:event_jButtonActivateLoginsActionPerformed

    private void jButtonAssignShiftsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignShiftsActionPerformed
        this.sgt.assignShifts();
    }//GEN-LAST:event_jButtonAssignShiftsActionPerformed

    private void jButtonRemoveShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveShiftActionPerformed

    private void jButtonConsultUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultUCActionPerformed
        JAdminConsultarUCs consultarUCs = new JAdminConsultarUCs(this.sgt);
        consultarUCs.setVisible(true);
    }//GEN-LAST:event_jButtonConsultUCActionPerformed

    @Override
    public void update(Observable observable, Object o) {
        if(o instanceof Integer){
            int flag = (Integer) o;
            this.checkBoxes[flag].setSelected(true);
            this.disableFrom(flag+1);
            if(flag<4) this.buttons[flag+1].setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAdmin(new SGT()).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActivateLogins;
    private javax.swing.JButton jButtonAddShift;
    private javax.swing.JButton jButtonAssignShifts;
    private javax.swing.JButton jButtonConsultUC;
    private javax.swing.JButton jButtonImportTurnos;
    private javax.swing.JButton jButtonImportUCs;
    private javax.swing.JButton jButtonImportUtilizadores;
    private javax.swing.JButton jButtonRemoveShift;
    private javax.swing.JCheckBox jCheckBoxLoginsActive;
    private javax.swing.JCheckBox jCheckBoxShiftsAssigned;
    private javax.swing.JCheckBox jCheckBoxTurnosRegistados;
    private javax.swing.JCheckBox jCheckBoxUCsRegistadas;
    private javax.swing.JCheckBox jCheckBoxUsersRegistered;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
