/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.userInterface;

import main.sgt.SGT;
import main.sgt.UC;
import main.sgt.exceptions.InvalidUserTypeException;
import main.sgt.exceptions.UtilizadorJaExisteException;
import main.sgt.exceptions.UtilizadorNaoExisteException;
import main.sgt.exceptions.WrongCredentialsException;

import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author pedro
 */
public class JAlunoEscolherUC extends javax.swing.JFrame {

    private final SGT sgt;

    /**
     * Creates new form AlunoEscolherUC
     */
    public JAlunoEscolherUC(SGT sgt) {
        initComponents();
        this.sgt = sgt;
        try {
            this.sgt.login("A79003","password");
        } catch (WrongCredentialsException e) {
            e.printStackTrace();
        }
        updateUCNEscolhidas();
        updateUCEscolhidas();
    }

    private void updateUCNEscolhidas() {
        List<UC> uCsOfUser;
        try {
            uCsOfUser = this.sgt.getUCsOfUser();
        } catch (InvalidUserTypeException e) {
            e.printStackTrace();
            //TODO leave frame
            return;
        }
        List<UC> allUCs = this.sgt.getUCs();
        allUCs.removeAll(uCsOfUser);
        DefaultTableModel tModel = (DefaultTableModel) this.jTableUCNEscolhidas.getModel();
        while(allUCs.size()>tModel.getRowCount()){
            tModel.addRow(new String[1]);
        }
        while (allUCs.size()<tModel.getRowCount()){
            tModel.removeRow(tModel.getRowCount()-1);
        }
        int i=0;
        for(UC uc: allUCs){
            tModel.setValueAt(uc.getId(),i++,0);
        }
    }

    private void updateUCEscolhidas() {
        List<UC> uCsOfUser;
        try {
            uCsOfUser = this.sgt.getUCsOfUser();
        } catch (InvalidUserTypeException e) {
            e.printStackTrace();
            //TODO leave frame
            return;
        }
        DefaultTableModel tModel = (DefaultTableModel) this.jTableUCNEscolhidas.getModel();
        while(uCsOfUser.size()>tModel.getRowCount()){
            tModel.addRow(new String[1]);
        }
        while (uCsOfUser.size()<tModel.getRowCount()){
            tModel.removeRow(tModel.getRowCount()-1);
        }
        int i=0;
        for(UC uc: uCsOfUser){
            tModel.setValueAt(uc.getId(),i++,0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPaneUCNEscolhidas = new javax.swing.JScrollPane();
        jTableUCNEscolhidas = new javax.swing.JTable();
        jScrollPaneUCEscolhidas = new javax.swing.JScrollPane();
        jTableUCEscolhidas = new javax.swing.JTable();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableUCNEscolhidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UCs não escolhidas:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneUCNEscolhidas.setViewportView(jTableUCNEscolhidas);

        jTableUCEscolhidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UCs escolhidas:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneUCEscolhidas.setViewportView(jTableUCEscolhidas);

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonFechar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneUCNEscolhidas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAdicionar)
                            .addComponent(jButtonRemover))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPaneUCEscolhidas, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButtonAdicionar)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonRemover))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneUCEscolhidas, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneUCNEscolhidas, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButtonFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        int selectedRow = this.jTableUCNEscolhidas.getSelectedRow();
        String uc = (String) this.jTableUCNEscolhidas.getValueAt(selectedRow, 0);
        try {
            this.sgt.addAlunoToUC(this.sgt.getLoggedUser().getUserNum(),uc);
            DefaultTableModel tableModel = (DefaultTableModel) this.jTableUCNEscolhidas.getModel();
            tableModel.removeRow(selectedRow);
            this.jTableUCNEscolhidas.setModel(tableModel);
            tableModel = (DefaultTableModel) this.jTableUCEscolhidas.getModel();
            tableModel.addRow(new Object[]{uc});
            this.jTableUCEscolhidas.setModel(tableModel);
        } catch (UtilizadorJaExisteException e) {
            updateUCEscolhidas();
            updateUCNEscolhidas();
        }
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        int selectedRow = this.jTableUCEscolhidas.getSelectedRow();
        String uc = (String) this.jTableUCEscolhidas.getValueAt(selectedRow, 0);
        try {
            this.sgt.removeAlunoFromUC(this.sgt.getLoggedUser().getUserNum(),uc);
            DefaultTableModel tableModel;
            tableModel = (DefaultTableModel) this.jTableUCEscolhidas.getModel();
            tableModel.removeRow(selectedRow);
            this.jTableUCNEscolhidas.setModel(tableModel);

            tableModel = (DefaultTableModel) this.jTableUCNEscolhidas.getModel();
            tableModel.addRow(new Object[]{uc});
            this.jTableUCEscolhidas.setModel(tableModel);

        } catch (UtilizadorNaoExisteException e) {
            updateUCEscolhidas();
            updateUCNEscolhidas();
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAlunoEscolherUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAlunoEscolherUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAlunoEscolherUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAlunoEscolherUC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAlunoEscolherUC(new SGT()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneUCEscolhidas;
    private javax.swing.JScrollPane jScrollPaneUCNEscolhidas;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableUCEscolhidas;
    private javax.swing.JTable jTableUCNEscolhidas;
    // End of variables declaration//GEN-END:variables
}
