/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.userInterface;

import main.sgt.*;
import main.sgt.exceptions.InvalidUserTypeException;
import main.sgt.exceptions.WrongCredentialsException;

import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author pedro
 */
public class JAlunoEspecialMudarTurno extends javax.swing.JFrame {

    private SGT sgt;
    /**
     * Creates new form AlunoEspecialMudarTurno
     */
    public JAlunoEspecialMudarTurno(SGT sgt) {
        this.sgt = sgt;
        try {
            this.sgt.login("A79003","password");
        } catch (WrongCredentialsException e) {
            e.printStackTrace();
        }
        initComponents();
        initUCsComboBox();
        updateTurnosTable();
    }

    private void updateTurnosTable() {
        String uc = (String) this.jComboBoxUCs.getSelectedItem();
        if(uc==null) return;
        List<Turno> turnos = this.sgt.getTurnosOfUC(uc);
        try {
            turnos.removeAll(this.sgt.getTurnosUser());
        } catch (InvalidUserTypeException e) {
            System.out.println("INVALID USER");
            //TODO leave frame
            return;
        }
        DefaultTableModel tModel = (DefaultTableModel) this.jTableTurnos.getModel();
        while(turnos.size()>tModel.getRowCount()){
            tModel.addRow(new String[4]);
        }
        while (turnos.size()<tModel.getRowCount()){
            tModel.removeRow(tModel.getRowCount()-1);
        }
        int i=0;
        for (Turno t: turnos){
            StringBuilder dias = new StringBuilder();
            StringBuilder horasInicio = new StringBuilder();
            StringBuilder horasFim = new StringBuilder();
            for (TurnoInfo ti: t.getTurnoInfos()){
                dias.append(ti.getDia()).append("\n");
                horasInicio.append(ti.getHoraInicio()).append("\n");
                horasFim.append(ti.getHoraFim()).append("\n");
            }
            dias.setLength(Math.max(dias.length() - 1, 0));
            horasInicio.setLength(Math.max(horasInicio.length() - 1, 0));
            horasFim.setLength(Math.max(horasFim.length() - 1, 0));

            tModel.setValueAt(t.getId(),i,0);
            tModel.setValueAt(dias.toString(),i,1);
            tModel.setValueAt(horasInicio.toString(),i,2);
            tModel.setValueAt(horasFim.toString(),i,3);
        }
        this.jTableTurnos.setModel(tModel);
    }

    private void initUCsComboBox() {
        this.jComboBoxUCs.removeAllItems();
        List<UC> uCsOfUser;
        try {
            uCsOfUser = this.sgt.getUCsOfUser();
        } catch (InvalidUserTypeException e) {
            System.out.println("INVALID USER");
            //TODO Leave frame
            return;
        }
        this.jComboBoxUCs.removeAllItems();
        uCsOfUser.stream()
                 .map(UC::getId)
                 .forEach(this.jComboBoxUCs::addItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxUCs = new javax.swing.JComboBox<>();
        jLabelUCs = new javax.swing.JLabel();
        jScrollPaneTurnos = new javax.swing.JScrollPane();
        jTableTurnos = new javax.swing.JTable();
        jButtonMudar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxUCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUCsActionPerformed(evt);
            }
        });

        jLabelUCs.setText("UCs");

        jTableTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Turnos", "Dia", "Hora de Inicio", "Hora de Fim"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneTurnos.setViewportView(jTableTurnos);

        jButtonMudar.setText("Mudar");
        jButtonMudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMudarActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxUCs, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                                .addComponent(jButtonMudar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUCs)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPaneTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelUCs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUCs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMudar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFechar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxUCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUCsActionPerformed
        updateTurnosTable();
    }//GEN-LAST:event_jComboBoxUCsActionPerformed

    private void jButtonMudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMudarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMudarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAlunoEspecialMudarTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAlunoEspecialMudarTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAlunoEspecialMudarTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAlunoEspecialMudarTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAlunoEspecialMudarTurno(new SGT()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonMudar;
    private javax.swing.JComboBox<String> jComboBoxUCs;
    private javax.swing.JLabel jLabelUCs;
    private javax.swing.JScrollPane jScrollPaneTurnos;
    private javax.swing.JTable jTableTurnos;
    // End of variables declaration//GEN-END:variables
}
